spring:
  datasource:
    url: jdbc:mysql://47.102.37.165:3306/train?useSSL=false&serverTimezone=UTC
    username: train2019gz
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
  - classpath:/mappers/**/*.xml