spring:
  datasource:
    url: jdbc:mysql://185.13.148.126:3316/train?useSSL=false&serverTimezone=UTC
    username: train2019gz
    password: train2019gzdHJhaW4yMDE5Z3o
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
  - classpath:/mappers/**/*.xml